# Generated by Django 4.2.11 on 2024-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('is_2fa', models.BooleanField(null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('two_factor_secret', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('IN_GAME', 'In_Game')], default='OFFLINE', max_length=100)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
