# Generated by Django 4.2.11 on 2024-03-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_option', models.CharField(choices=[('CLASSIC', 'Classic'), ('SPEED', 'Speed')], max_length=100)),
                ('game_mode', models.CharField(choices=[('TWO_PLAYER', '2P Mode'), ('NORMAL', 'Normal mode'), ('TOURNAMENT', 'Tournament mode')], max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose')], max_length=50)),
                ('opponent_id', models.IntegerField(null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user_id', 'game_id'), name='PK_PARTICIPANT'),
        ),
    ]
